#!/Library/Frameworks/Python.framework/Versions/Current/bin/python
#make this file exectutable

#============= standard library imports ========================
import os
import shutil
import sys
import plistlib
import argparse
#============= local library imports  ==========================


root = os.getcwd()

class Installer(object):
    prefix = None
    name = None
    icon_name = None
    def __init__(self, prefix, name, icon_name = None):
        self.prefix = prefix
        self.name = name
        self.icon_name = icon_name

    def install(self):
        if sys.platform == 'darwin':
            from BuildApplet import buildapplet
            print 'Building {}.py'.format(self.name)
            
            sys.argv[1:] = [os.path.join(root, '{}.py'.format(self.name))]
            buildapplet()

            #===================================================================
            # run build applet
            #===================================================================
            dist_root = os.path.join(root, '{}.app/Contents'.format(self.prefix))


            if self.icon_name is not None:
                icon_file = '{}.icns'.format(self.icon_name)

            else:
                icon_file = '{}_icon.icns'.format(self.prefix)


            #===================================================================
            # copy files
            #===================================================================

            icon = os.path.join(root, 'resources', icon_file)
            if os.path.isfile(icon):
                shutil.copyfile(icon,
                            os.path.join(dist_root, 'Resources', icon_file))
            else:
                print '----- No Icon File for {} -----'.format(self.prefix)

            #===================================================================
            # #edit the plist
            #===================================================================

            info_plist = os.path.join(dist_root, 'Info.plist')
            tree = plistlib.readPlist(info_plist)


            tree['CFBundleIconFile'] = icon_file
            tree['CFBundleName'] = self.name

            plistlib.writePlist(tree, info_plist)
            print 'Created {}'.format(os.path.join(root, '{}.py'.format(self.name)))
            #===================================================================
            # change app prefix
            #===================================================================
#            p1 = os.path.join(root, '{}.app'.format(self.prefix))
#            p2 = os.path.join(root, '{}.app'.format(self.name))
#
#            if os.path.exists(p2):
#                shutil.rmtree(p2)
#            os.rename(p1, p2)


def install_pychron_suite():
    

    parser = argparse.ArgumentParser(description = 'Install Pychron')
    
    parser.add_argument('-d', '--data', action='store_true',
                        help = 'overwrite the current pychron_data directory')
    parser.add_argument('-f', '--force-data', action='store_true',
                        help = 'dont ask to overwrite the data dir, just do it')
    parser.add_argument('-a', '--apps-only', action='store_true',
                        help = 'only create the app bundles')
    args = parser.parse_args()
    
    
    i=Installer('pychron_beta', 'pychron_beta')
    i.install()
    
    i.prefix='remote_hardware_server'
    i.name='remote_hardware_server'
    i.install()
    

    #move data into place
    if args.apps_only:
        return 
    
    data=os.path.join(os.getcwd(),'data')
    home=os.path.expanduser('~')
    dst=os.path.join(home, 'pychron_data_beta')

    try:
        shutil.copytree(data, dst)
        print 'copying {} -> {}'.format(data,dst)
    except OSError:
        if args.data:
            rin='y'
            if not args.force_data:
                rin=raw_input('overwrite exisiting data y/n [y] >> ').strip().lower()
                
            if len(rin)==0 or rin in ['y','yes']:
                print 'copying {} -> {}'.format(data,dst)   
                shutil.rmtree(dst, ignore_errors=True)
                shutil.copytree(data, dst)
        

def cli_install():
    
    parser = argparse.ArgumentParser(description = 'Create a new Launchable Application')
    parser.add_argument('prefix',
                        #metavar = 'prefix', 
                        type = str, nargs = '?',
                        help = 'Prefix name. used to identify the icon file and the launch script eg. pychron'
                        )
    parser.add_argument('name',
                        #metavar = 'name', 
                        type = str, nargs = '?',
                        help = 'Name of the application bundle eg. Pychron')

    parser.add_argument('--icon', type = str, nargs = '?',
                        help = 'icon file name')
    args = parser.parse_args()

    i = Installer(args.prefix, args.name, args.icon)
    i.install()
    
if __name__ == '__main__':
    
#    cli_install()
    
    install_pychron_suite()
#============= EOF =====================================
