#============= enthought library imports =======================
from traits.api import HasTraits

#============= standard library imports ========================

#============= local library imports  ==========================
from report import Report
class ReportManager(HasTraits):
    def create(self):
        r = Report()
        r.cover_text = 'This report was generated by Reporter by Jake Ross'
        r.add_page_break()
        r.add_heading('Introduction', 'Heading1')
        r.add_heading('subheading', 'Heading2')
        r.add_paragraph('this is a paragragh' * 20)
        r.add_spacer()
        r.add_heading('Appendix A:', 'Heading1')
        r.add_spacer()



if __name__ == '__main__':
    r = ReportManager()
    r.configure_traits()
#============= EOF =============================================
