#===============================================================================
# Copyright 2011 Jake Ross
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#===============================================================================



#============= enthought library imports =======================
from traits.api import HasTraits

#============= standard library imports ========================

#============= local library imports  ==========================
from report import Report
class ReportManager(HasTraits):
    def create(self):
        r = Report()
        r.cover_text = 'This report was generated by Reporter by Jake Ross'
        r.add_page_break()
        r.add_heading('Introduction', 'Heading1')
        r.add_heading('subheading', 'Heading2')
        r.add_paragraph('this is a paragragh' * 20)
        r.add_spacer()
        r.add_heading('Appendix A:', 'Heading1')
        r.add_spacer()



if __name__ == '__main__':
    r = ReportManager()
    r.create()
#    r.configure_traits()
#============= EOF =============================================
